"""quiz.py — A dynamic multiple-choice quiz for Data Science students.

Questions are generated by the Claude API each time you run the quiz.
Students choose a difficulty level: beginner, intermediate, or advanced.
Each quiz has 10 questions (2 per topic) at the chosen difficulty.

Topics: lists, numpy, built_in_functions, functions, data_types
"""

import random
from database import setup_database, save_result, DB_FILE
from generate_question import generate_question

# All 5 topics — 2 questions per topic = 10 questions total
TOPICS = ["lists", "numpy", "built_in_functions", "functions", "data_types"]
QUESTIONS_PER_TOPIC = 2
DIFFICULTY_LEVELS = ["beginner", "intermediate", "advanced"]


def generate_quiz_questions(difficulty='beginner'):
    """Generate 10 quiz questions (2 per topic) at the given difficulty.

    Returns a list of question dicts:
    [{"question": ..., "options": {...}, "answer": ..., "topic": ..., "difficulty": ...}, ...]
    """
    questions = []

    # Shuffle topics so the quiz order is different each time
    topics_shuffled = TOPICS.copy()
    random.shuffle(topics_shuffled)

    for topic in topics_shuffled:
        for _ in range(QUESTIONS_PER_TOPIC):
            try:
                q = generate_question(topic, difficulty=difficulty)
                questions.append(q)
            except Exception as e:
                print(f"   ⚠️  Failed to generate a question for {topic}: {e}")

    return questions


def run_quiz(difficulty='beginner'):
    """Run the quiz: generate questions, ask them, save each result, show score.

    Args:
        difficulty: 'beginner', 'intermediate', or 'advanced'
    """

    setup_database()

    student_name = input("Enter your name: ").strip()

    print(f"\n🤖 Generating {len(TOPICS) * QUESTIONS_PER_TOPIC} {difficulty} questions...")
    print("   This may take a moment.\n")

    questions = generate_quiz_questions(difficulty)

    if not questions:
        print("❌ Could not generate any questions. Check your API connection.")
        return

    score = 0
    total = len(questions)
    print("=" * 50)
    print(f"       DATA SCIENCE QUIZ — {difficulty.upper()}")
    print("=" * 50)
    print(f"\nThere are {total} questions. Type A, B, C, or D to answer.\n")

    for i, q in enumerate(questions, start=1):
        print(f"Question {i}: {q['question']}")
        for letter, text in q["options"].items():
            print(f"   {letter}. {text}")

        while True:
            user_answer = input("\nYour answer (A/B/C/D): ").strip().upper()
            if user_answer in ("A", "B", "C", "D"):
                break
            print("Invalid input. Please type A, B, C, or D.")

        is_correct = (user_answer == q["answer"])

        save_result(student_name, q["topic"], q["question"], is_correct, difficulty)

        if is_correct:
            print("   ✅ Correct!\n")
            score += 1
        else:
            print(f"   ❌ Incorrect. The answer was {q['answer']}.\n")

    print("=" * 50)
    print(f"           FINAL SCORE: {score}/{total}")
    percentage = (score / total) * 100
    print(f"           That's {percentage:.0f}%")

    if percentage == 100:
        print("           Perfect score! 🎉")
    elif percentage >= 80:
        print("           Great job! 🌟")
    elif percentage >= 60:
        print("           Good effort! Keep practicing.")
    else:
        print("           Keep studying — you'll get it!")
    print("=" * 50)
    print(f"\n(Your results have been saved to {DB_FILE})")


if __name__ == "__main__":
    # Let the user pick a difficulty level
    print("=" * 50)
    print("       DATA SCIENCE BASICS — PYTHON QUIZ")
    print("=" * 50)
    print("\nChoose your difficulty level:")
    print("   1. Beginner     (basic syntax and definitions)")
    print("   2. Intermediate (applying concepts, reading code)")
    print("   3. Advanced     (edge cases, tricky behavior)")

    while True:
        choice = input("\nEnter 1, 2, or 3: ").strip()
        if choice in ("1", "2", "3"):
            break
        print("Please enter 1, 2, or 3.")

    difficulty = DIFFICULTY_LEVELS[int(choice) - 1]
    run_quiz(difficulty)
